### ISSUE TITLE
dhcpuserid.py setup fails

### ISSUE THREAD

**Issue by wormfishin** [tdmakepeace/PaloAltoHomeUserID#6]
I'm getting the following error when I try to run python ./dhcpuserid.py setup

`userid@userid:~/PaloAltoHomeUserID$` source env/bin/activate
(env) userid@userid:~/PaloAltoHomeUserID$ python ./dhcpuserid.py setup
  File "./dhcpuserid.py", line 527
    cur2.close()
               ^
TabError: inconsistent use of tabs and spaces in indentation`

**Comment by tdmakepeace** [comment]
Thanks, fixed in the master rev.
Issue related to no groups being created in the GUI.
The Dev branch already had the fix, but also is a bit different, as it is all in a single script with threading.
